# Written for PostgreSQL 10.5 at 2018-11-11
---
# Ensure that a dataset has been created for PostgreSQL
- name: ensure presence of postgresql ZFS dataset
  when: delegated_dataset is succeeded
  zfs:
    name: '{{ ansible_mounts.0.device }}/data/pgsql'
    state: present
    extra_zfs_properties:
      mountpoint: /var/pgsql
      recordsize: 16k

# Ensure that PostgreSQL server mountpoint is secure
- name: ensure secure permissions on postgresql ZFS mountpoint
  file:
    path: /var/pgsql
    state: directory
    owner: 907
    group: 907
    mode: 0700

# Ensure that PostgreSQL server is installed
- name: ensure presence of {{ postgresql_server }}
  pkgin:
    name: '{{ postgresql_server }}'
  notify: restart postgresql-server

# Ensure that PostgreSQL server is configured to take advantage of ZFS
- name: ensure that postgresql-server is properly configured
  template:
    src: '{{ item }}'
    dest: '/var/pgsql/data/{{ item }}'
    owner: postgres
    group: postgres
    mode: 0600
  with_items:
    - postgresql.conf
    - pg_hba.conf
    - pg_ident.conf
  notify: restart postgresql-server

# Ensure that PostgreSQL server is enabled in SMF
- name: ensure that postgresql-server is enabled
  service:
    name: 'svc:/pkgsrc/postgresql:default'
    enabled: true
