---
- name: ensure presence of redis ZFS dataset
  when: delegate_dataset is succeeded
  zfs:
    name: '{{ zone_dataset }}/redis'
    state: present
    extra_zfs_properties:
      mountpoint: '{{ (default_redis|combine(redis, recursive=True)).config.dir }}'

- name: ensure that redis has been installed
  notify: restart redis
  pkgin:
    name: redis

- name: ensure that redis has been configured
  notify: restart redis
  template:
    src: redis.conf
    dest: /opt/local/etc/redis.conf
    owner: root
    group: root
    mode: 0644

- name: ensure that redis has been enabled
  register: redis_enabled
  service:
    name: 'svc:/pkgsrc/redis:default'
    enabled: true
