---
- name: ensure that clamav has been installed
  notify: restart clamav
  pkgin:
    name: clamav

- name: ensure that clamav has been enabled
  register: clamav_enabled
  service:
    name: 'svc:/pkgsrc/clamav:freshclamd svc:/pkgsrc/clamav:clamd'
    enabled: true
