---
- hosts: ansible
  roles:
  - ansible

- hosts: common
  roles:
  - common

- hosts: ghost
  roles:
  - ghost

- hosts: mysql
  roles:
  - mysql

- hosts: neo4j
  roles:
  - neo4j

- hosts: nginx
  roles:
  - nginx

- hosts: postgresql
  roles:
  - postgresql
