---
- name: ensure that samba has been installed
  notify: restart samba
  pkgin:
    name: samba

- name: ensure that samba has been configured
  notify: restart samba
  template:
    src: smb.conf
    dest: /opt/local/etc/samba/smb.conf
    mode: 0644
    owner: root
    group: root

- name: ensure that the log directory ({{ (default_samba|combine(samba, recursive=True)).global["log file"] | dirname }}) exists
  when: (default_samba|combine(samba, recursive=True)).global['log file'] is defined
  file:
    path: '{{ (default_samba|combine(samba, recursive=True)).global["log file"] | dirname }}'
    state: directory
    owner: root
    group: root
    mode: 0750

- name: ensure that samba has been enabled
  register: samba_enabled
  service:
    name: 'svc:/pkgsrc/samba:smbd svc:/pkgsrc/samba:nmbd'
    enabled: true
