---
- name: ensure that pkgin managed software has been installed
  pkgin:
    name:
    - git
    - libyaml
    - py37-bcrypt
    - py37-cryptography
    - py37-nacl
    - py37-pip

- name: ensure that pip has been updated to its latest version
  pip:
    name: pip
    state: latest
    executable: pip # Ansible is confused by SmartOS' pkgin managed pip and needs help here

- name: ensure that ansible has been updated to its latest version
  pip:
    name:
    - ansible
    - netaddr
    - redis
    state: latest

- name: ensure existance of ansible configuration directory
  file:
    path: /etc/ansible
    state: directory
    owner: root
    group: root
    mode: 0755

- name: ensure that ansible has been configured
  template:
    src: ansible.cfg
    dest: /etc/ansible/ansible.cfg
    owner: root
    group: root
    mode: 0644

- name: ensure that an OpenSSH ed25519 keypair exists for root
  openssh_keypair:
    path: /root/.ssh/id_ed25519
    type: ed25519
    owner: root
    group: root
