---
- name: ensure that unnecessary default services are disabled
  service:
    name: 'svc:/network/inetd:default svc:/system/sac:default'
    enabled: false

- name: ensure that the delegated ZFS filesystem is unmounted
  ignore_errors: true
  notify: remove delegated mountpoint
  register: delegate_dataset
  zfs:
    name: '{{ ansible_mounts.0.device }}/data'
    state: present
    extra_zfs_properties:
      mountpoint: none

- name: ensure that useradd is properly configured
  template:
    src: useradd
    dest: /etc/default/useradd
    owner: root
    group: root
    mode: 0644

- name: ensure that inputrc is properly configured
  template:
    src: inputrc
    dest: /etc/inputrc
    owner: root
    group: root
    mode: 0644

- name: ensure that sshd is securely configured
  notify: restart sshd
  template:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644

- name: ensure that the pkgsrc cache has been updated
  pkgin:
    update_cache: true
