---
- name: fail when not SmartOS
  when: ansible_distribution != 'SmartOS'
  fail:
    msg: This role is intended to only be used on SmartOS distributions

- name: determine the zone uuid
  command: sysinfo
  register: sysinfo_command

- name: set the zone dataset fact
  set_fact:
    zone_dataset: 'zones/{{ (sysinfo_command.stdout | from_json).UUID }}/data'

- name: ensure that unnecessary default services are disabled
  service:
    name: 'svc:/network/inetd:default svc:/system/sac:default'
    enabled: false

- name: ensure that the delegated ZFS filesystem is unmounted
  ignore_errors: true
  notify: remove delegated mountpoint
  register: delegate_dataset
  zfs:
    name: '{{ zone_dataset }}'
    state: present
    extra_zfs_properties:
      mountpoint: none

- name: ensure that the home ZFS dataset exists
  when: home_dataset and delegate_dataset is succeeded
  include_tasks: home_dataset.yml

- name: ensure that useradd is properly configured
  template:
    src: useradd
    dest: /etc/default/useradd
    owner: root
    group: root
    mode: 0644

- name: ensure that inputrc is properly configured
  template:
    src: inputrc
    dest: /etc/inputrc
    owner: root
    group: root
    mode: 0644

- name: ensure that sshd is securely configured
  notify: restart sshd
  template:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644

- name: ensure that the root home directory is secured
  file:
    path: /root
    state: directory
    owner: root
    group: root
    mode: 0750

- name: ensure that the pkgsrc cache has been updated
  pkgin:
    update_cache: true
