---
- name: ensure that unnecessary default services are disabled
  service:
    name: 'svc:/network/inetd:default svc:/system/sac:default'
    enabled: false

- name: ensure that the delegated ZFS dataset is unmounted
  zfs:
    name: '{{ ansible_mounts.0.device }}/data'
    state: present
    extra_zfs_properties:
      mountpoint: none
  ignore_errors: true
  register: delegated_dataset
  notify: remove delegated mountpoint

- name: ensure that useradd is configured to manage ZFS datasets
  when: delegated_dataset is succeeded
  template:
    src: useradd
    dest: /etc/default/useradd
    owner: root
    group: root
    mode: 0644

- name: ensure that inputrc is properly configured
  template:
    src: inputrc
    dest: /etc/inputrc
    owner: root
    group: root
    mode: 0644

- name: ensure that sshd is securely configured
  template:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart sshd

- name: ensure that the pkgsrc cache has been updated
  pkgin:
    update_cache: true
