---
- name: disable unnecessary default services
  service:
    name: 'svc:/network/inetd:default svc:/system/sac:default'
    enabled: false
- name: unmount delegated ZFS dataset
  zfs:
    name: '{{ ansible_mounts.0.device }}/data'
    state: present
    extra_zfs_properties:
      mountpoint: none
  ignore_errors: true
  notify: remove delegated mountpoint
- name: update sshd configuration
  template:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart sshd
