---
default_mysql:
  server: mysql
  recordsize: 16k
  config:
    client:
      port: 3306
      socket: /tmp/mysql.sock
      default-character-set: utf8mb4
    mysql:
      no-auto-rehash:
    mysqlhotcopy:
      interactive-timeout:
    mysqldump:
      quick:
      max_allowed_packet: 16M
    myisamchk:
      key_buffer_size: 128M
      sort_buffer_size: 128M
      read_buffer: 2M
      write_buffer: 2M
    mysqld:
#------------------
# General Settings
#------------------
      user: mysql
      group: mysql
      port: 3306
      basedir: /opt/local
      datadir: /var/mysql
      socket: /tmp/mysql.sock
      bind-address: '127.0.0.1'
      default-storage-engine: innodb
      character-set-server: utf8
      skip-external-locking:
      log_warnings:
      skip_name_resolve:
      server-id: 1

#-----------------
# MyISAM Settings
#-----------------
      key_buffer_size: 16M
      sort_buffer_size: 1M
      read_buffer_size: 1M
      read_rnd_buffer_size: 4M
      myisam_sort_buffer_size: 64M

#-----------------
# InnoDB Settings
#-----------------
      innodb_data_home_dir: /var/mysql
      innodb_log_group_home_dir: /var/mysql
      innodb_data_file_path: ibdata1:100M:autoextend
      innodb_buffer_pool_size: 16M
      innodb_log_file_size: 400M
      innodb_log_buffer_size: 8M
      innodb_flush_log_at_trx_commit: 2
      innodb_lock_wait_timeout: 50
      innodb_file_per_table:
      innodb_doublewrite: 0
      innodb_io_capacity: 1500
      innodb_read_io_threads: 8
      innodb_write_io_threads: 8

#-------------------------
# Slow Query Log Settings
#-------------------------
#     use_global_long_query_time: 1
#     long_query_time: 0.5
      slow_query_log_file: /var/log/mysql/slowquery.log
      slow_query_log: 1

#------------------------------
# Other General MySQL Settings
#------------------------------
      table_open_cache: 512
      thread_cache_size: 1000
#     query_cache_size: 16M
#     query_cache_strip_comments:
      query_cache_type: 0
      back_log: 64
      thread_concurrency: 32
      tmpdir: /tmp
      max_connections: 1000
      max_allowed_packet: 24M
      max_join_size: 4294967295
      net_buffer_length: 2K
      thread_stack: 256K
      tmp_table_size: 64M
      max_heap_table_size: 64M

#-------------------------------------------------------------
# Replication Settings (master to slave, disabled by default)
# See: http://wiki.joyent.com/wiki/display/jpc2/Replication
#-------------------------------------------------------------
      binlog_format: mixed
      log-bin: /var/log/mysql/bin.log
#     log-bin-index: /var/log/mysql/log-bin.index
      log-error: /var/log/mysql/error.log
#     report-host: percona
#     relay_log_purge: 1
      expire_logs_days: 7
#     slave-skip-errors: 1062
#     binlog-ignore-db: mysql
